{{ range .Values.projects }}

{{ $.Files.Get "files/project-config/{{ .name }}.yaml" }}


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | default "test-project"}}
spec:
  project: {{ index $.Values "argo-cd-info" "project-project" }}
  source:
    repoURL: {{ .projectConfigRepo }}
    path: .
    targetRevision: master
  destination:
    namespace: {{ index $.Values "argo-cd-info" "project-project" }}-ns
    name: {{ .name }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true

{{end}}
